name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Package
        run: make build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: bin/myapp

