name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build docker-compose
        run: docker-compose build
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Wait for services to be ready
        run: docker-compose ps
      - name: Run Tests
        run: |
          docker exec myapp bash -c 'make test'
      - name: Stop Docker Compose
        run: docker-compose down

